title: Rejeesh S
logo: /assets/img/logo1.png
description: Software developer with an extensive experience in desktop application developement.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
